name: Lint & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # only support Python 3.10+ due to type hinting
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Analysing the code with black
      run: |
        python -m black --check --line-length 120 .
    - name: Analysing imports with isort
      run : |
       python -m isort --check .
    - name: Running test suite
      run: |
        python -m pytest .
      if: always()